# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "dev/us-east-1/vpc/blue/terraform.tfstate"
    region         = "us-east-1"
    bucket         = "terraform-state-evilshatner-dev-us-east-1"
  }
}
